# Generated by Django 6.0.7 on 2026-08-28 04:24

from django.db import migrations


# Map product names (case-insensitive substring) to their committed static image paths
PRODUCT_IMAGE_MAP = [
    ('decorated cupcake',    '/static/images/IMG-20260629-WA0042.jpeg'),
    ('non-decorated cupcake', '/static/images/IMG-20260629-WA0043.jpg'),
    ('crunchy coated peanut', '/static/images/IMG-20260827-WA0018.jpg'),
    ('chin chin (big',        '/static/images/IMG-20260827-WA0006.jpg'),
    ('chin chin (medium',     '/static/images/IMG-20260827-WA0004.jpg'),
    ('coated peanut (portion','/static/images/IMG-20260827-WA0016.jpg'),
]


def fix_image_urls(apps, schema_editor):
    Product = apps.get_model('core', 'Product')
    for product in Product.objects.all():
        name_lower = product.name.lower()
        # Skip products that already have a working static or external URL
        if product.image_url and not product.image_url.startswith('/media/'):
            continue
        for keyword, static_url in PRODUCT_IMAGE_MAP:
            if keyword in name_lower:
                product.image_url = static_url
                product.save()
                break


def reverse_fix(apps, schema_editor):
    pass  # Non-destructive: no rollback needed


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_product_image_alter_product_image_url'),
    ]

    operations = [
        migrations.RunPython(fix_image_urls, reverse_fix),
    ]

